--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1

-- Started on 2021-01-31 23:28:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3043 (class 1262 OID 16394)
-- Name: clojure; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE clojure3 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'English_United States.1252';


ALTER DATABASE clojure3 OWNER TO postgres;

\connect clojure3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 16442)
-- Name: images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.images (
    id integer NOT NULL,
    src character varying(50) NOT NULL,
    alt character varying(50) NOT NULL
);


ALTER TABLE public.images OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16491)
-- Name: images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16458)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    ordertime date NOT NULL,
    userid integer NOT NULL,
    isfinished boolean DEFAULT false NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16489)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 16468)
-- Name: orders_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_product (
    id integer NOT NULL,
    orderid integer NOT NULL,
    productid integer NOT NULL,
    qty integer NOT NULL,
    productprice integer NOT NULL
);


ALTER TABLE public.orders_product OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16487)
-- Name: orders_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 16434)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    imageid integer,
    description character varying(1000) NOT NULL,
    producttypeid integer NOT NULL,
    price integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16485)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16429)
-- Name: producttypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producttypes (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(1000) NOT NULL,
    imgid integer DEFAULT 1
);


ALTER TABLE public.producttypes OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 16483)
-- Name: producttypes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producttypes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producttypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 16403)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(40) NOT NULL,
    password character varying(100) NOT NULL,
    firstname character varying(40) NOT NULL,
    lastname character varying(50) NOT NULL,
    mail character varying(100) NOT NULL,
    isactive boolean NOT NULL,
    isadmin boolean NOT NULL,
    address character varying(100) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 16401)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 3044 (class 0 OID 0)
-- Dependencies: 200
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 2883 (class 2604 OID 16406)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 2898 (class 2606 OID 16446)
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- TOC entry 2900 (class 2606 OID 16462)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 2902 (class 2606 OID 16472)
-- Name: orders_product orders_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_product
    ADD CONSTRAINT orders_product_pkey PRIMARY KEY (id);


--
-- TOC entry 2896 (class 2606 OID 16441)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 2893 (class 2606 OID 16433)
-- Name: producttypes producttype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producttypes
    ADD CONSTRAINT producttype_pkey PRIMARY KEY (id);


--
-- TOC entry 2889 (class 2606 OID 16408)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2891 (class 2606 OID 16410)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 2894 (class 1259 OID 16457)
-- Name: fki_product_productid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_product_productid ON public.products USING btree (producttypeid);


--
-- TOC entry 2903 (class 2606 OID 16495)
-- Name: producttypes imageid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producttypes
    ADD CONSTRAINT imageid FOREIGN KEY (imgid) REFERENCES public.images(id) NOT VALID;


--
-- TOC entry 2906 (class 2606 OID 16478)
-- Name: orders order_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT order_users FOREIGN KEY (userid) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 2905 (class 2606 OID 16447)
-- Name: products prodcut_imageId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "prodcut_imageId" FOREIGN KEY (imageid) REFERENCES public.images(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2907 (class 2606 OID 16473)
-- Name: orders_product product_orders; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_product
    ADD CONSTRAINT product_orders FOREIGN KEY (orderid) REFERENCES public.orders(id);


--
-- TOC entry 2904 (class 2606 OID 16452)
-- Name: products product_productid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT product_productid FOREIGN KEY (producttypeid) REFERENCES public.producttypes(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2021-01-31 23:28:21

--
-- PostgreSQL database dump complete
--

